name: Ensure TheKillerBunny's email is not exposed
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Ensure TheKillerBunny's email is not exposed
        run: "! [[ $(git log --author ${{ secrets.BUNNY_PERSONAL_EMAIL }}) ]]"
